version: 2.23.0
services:
    server:
        image: httpd:latest
        container_name: my-apache-compose
        ports:
            - '8080:80'
        volumes:
            - ./website:/usr/local/apache2/htdocs
        depends_on:
            - db
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: gestion
            MYSQL_USER: toto
            MYSQL_PASSWORD: 1234
